"""2

Revision ID: 488059fe3a34
Revises: a84a83fa266a
Create Date: 2026-04-26 17:03:30.104537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488059fe3a34'
down_revision: Union[str, Sequence[str], None] = 'a84a83fa266a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scustom', 'password',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('sflight', 'fldate',
               existing_type=sa.DATE())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sflight', 'fldate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('scustom', 'password',
               existing_type=sa.VARCHAR(length=20))
    # ### end Alembic commands ###
