"""init.

Revision ID: 4e95d9fb8422
Revises: 
Create Date: 2026-01-24 00:19:23.522635

"""
import random
from datetime import datetime
from pathlib import Path
from typing import Sequence, Union

import sqlalchemy as sa
from dotenv import dotenv_values
from faker import Faker
from sqlalchemy import Date, Integer, Numeric, String, Time, column, table

from alembic import op

env_path = Path(__file__).parent.parent.parent / 'src' / '.env'
print(env_path)
mandt=dotenv_values(env_path)['MANDT']


# revision identifiers, used by Alembic.
revision: str = '4e95d9fb8422'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sairport',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('mandt', 'id')
    )
    op.create_table('scarr',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('carrid', sa.Integer(), nullable=False),
    sa.Column('carrname', sa.String(length=20), nullable=True),
    sa.Column('carrcode', sa.String(length=5), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('mandt', 'carrid')
    )
    op.create_table('scustom',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('mandt', 'phone')
    )
    op.create_table('spfli',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('carrid', sa.Integer(), nullable=False),
    sa.Column('connid', sa.String(length=4), nullable=False),
    sa.Column('countryfr', sa.String(length=100), nullable=False),
    sa.Column('cityfrom', sa.String(length=100), nullable=False),
    sa.Column('airpfrom', sa.Integer(), nullable=False),
    sa.Column('countryto', sa.String(length=100), nullable=False),
    sa.Column('cityto', sa.String(length=100), nullable=False),
    sa.Column('airpto', sa.Integer(), nullable=False),
    sa.Column('fltime', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['mandt', 'airpfrom'], ['sairport.mandt', 'sairport.id'] ),
    sa.ForeignKeyConstraint(['mandt', 'airpto'], ['sairport.mandt', 'sairport.id'] ),
    sa.ForeignKeyConstraint(['mandt', 'carrid'], ['scarr.mandt', 'scarr.carrid'] ),
    sa.PrimaryKeyConstraint('mandt', 'carrid', 'connid')
    )
    op.create_table('sflight',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('carrid', sa.Integer(), nullable=False),
    sa.Column('connid', sa.String(length=4), nullable=False),
    sa.Column('fldate', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('planetype', sa.String(length=10), nullable=True),
    sa.Column('seatsmax', sa.Integer(), nullable=True),
    sa.Column('seatsocc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mandt', 'carrid', 'connid'], ['spfli.mandt', 'spfli.carrid', 'spfli.connid'] ),
    sa.PrimaryKeyConstraint('mandt', 'carrid', 'connid', 'fldate')
    )
    op.create_table('sbook',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('carrid', sa.Integer(), nullable=False),
    sa.Column('connid', sa.String(length=4), nullable=False),
    sa.Column('fldate', sa.Date(), nullable=False),
    sa.Column('bookid', sa.Integer(), nullable=False),
    sa.Column('customid', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['mandt', 'carrid', 'connid', 'fldate'], ['sflight.mandt', 'sflight.carrid', 'sflight.connid', 'sflight.fldate'] ),
    sa.ForeignKeyConstraint(['mandt', 'carrid'], ['scarr.mandt', 'scarr.carrid'] ),
    sa.ForeignKeyConstraint(['mandt', 'carrid'], ['scarr.mandt', 'scarr.carrid'] ),
    sa.ForeignKeyConstraint(['mandt', 'customid'], ['scustom.mandt', 'scustom.phone'] ),
    sa.PrimaryKeyConstraint('mandt', 'carrid', 'connid', 'fldate', 'bookid')
    )

    conn = op.get_bind()
    add(conn,20)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sbook')
    op.drop_table('sflight')
    op.drop_table('spfli')
    op.drop_table('scustom')
    op.drop_table('scarr')
    op.drop_table('sairport')
    # ### end Alembic commands ###

def add(conn, count):
    """Миграция данных."""
    # scustom = table(
    #     'scustom',
    #     column('mandt', String),
    #     column('phone', String),
    #     column('name', String)
    # )

    sairport = table(
        'sairport',
        column('mandt', String),
        column('id', Integer),
        column('name', String),
        column('timezone', String)
    )

    spfli = table(
        'spfli',
        column('mandt', String),
        column('carrid', Integer),
        column('connid', String),
        column('countryfr', String),
        column('cityfrom', String),
        column('airpfrom', Integer),
        column('countryto', String),
        column('cityto', String),
        column('airpto', Integer),
        column('fltime', Time)
    )

    sflight = table(
        'sflight',
        column('mandt', String),
        column('carrid', Integer),
        column('connid', String),
        column('fldate', Date),
        column('price', Numeric),
        column('currency', String),
        column('planetype', String),
        column('seatsmax', Integer),
        column('seatsocc', Integer)
    )

    scarr = table(
        'scarr',
        column('mandt', String),
        column('carrid', Integer),
        column('carrname', String),
        column('carrcode', String),
        column('url', String)
    )

    # sbook = table(
    #     'sbook',
    #     column('mandt', String),
    #     column('carrid', Integer),
    #     column('connid', String),
    #     column('fldate', Date),
    #     column('bookid', Integer),
    #     column('customid', String)
    # )

    utc_timezones = [
        'UTC-12', 'UTC-11', 'UTC-10', 'UTC-9:30', 'UTC-9', 'UTC-8', 
        'UTC-7', 'UTC-6', 'UTC-5', 'UTC-4', 'UTC-3:30', 'UTC-3', 
        'UTC-2', 'UTC-1', 'UTC±0', 'UTC+1', 'UTC+2', 'UTC+3', 
        'UTC+3:30', 'UTC+4', 'UTC+4:30', 'UTC+5', 'UTC+5:30', 
        'UTC+5:45', 'UTC+6', 'UTC+6:30', 'UTC+7', 'UTC+8', 
        'UTC+8:45', 'UTC+9', 'UTC+9:30', 'UTC+10', 'UTC+10:30', 
        'UTC+11', 'UTC+12', 'UTC+12:45', 'UTC+13', 'UTC+14'
    ]
    
    faker = Faker()        

    connids = []
    while len(connids) < count*3:
        connid = faker.numerify(text='####')
        if connid not in connids:
            connids.append(connid)

    names = []
    while len(names) < count:
        name = faker.city()[:3].upper()
        if name not in names:
            names.append(name)

    for i in range(count):
        conn.execute(
            sairport.insert()
            .values(
            mandt=mandt,
            id=i+1,
            name=names[i],
            timezone=random.choice(utc_timezones)))

    for i in range(count*3):
        carrname = faker.word().capitalize()
        conn.execute(
            scarr.insert()
            .values(
            mandt=mandt,
            carrid=i, 
            carrname=carrname, 
            carrcode=carrname[:2].upper(), 
            url=faker.url()))
        
    for i in range(count):
        cityfrom=faker.city()
        cityto=faker.city()
        fldate=faker.future_date(end_date='+365d')
    
        for j in range(random.randint(1,3)):                     
            airpfrom=random.randint(1,count)
            airpto=random.randint(1,count)
            while airpto == airpfrom:
                    airpto=random.randint(1,count)  

            time = datetime.strptime(faker.time(), '%H:%M:%S').time()
            conn.execute(
            spfli.insert()
            .values(
                mandt = mandt,
                carrid=i*3+j,
                connid=connids[i*3+j],
                countryfr=faker.country(),
                cityfrom=cityfrom,
                airpfrom=airpfrom,
                countryto=faker.country(),
                cityto=cityto,
                airpto=airpto,
                fltime=time
                ))
    
            airpfrom=''
            airpto=''
        
            conn.execute(
            sflight.insert()
            .values(
                mandt=mandt,
                carrid=i*3+j,
                connid=connids[i*3+j],
                fldate=fldate,
                price=faker.pydecimal(left_digits=5,right_digits=2,positive=True,min_value=100,max_value=10000),
                currency=faker.currency()[0],
                planetype=faker.bothify(text='?').upper()+faker.numerify(text='###'),
                seatsmax=random.randint(180,200),
                seatsocc=random.randint(1,180)
            ))
