"""1.

Revision ID: a84a83fa266a
Revises: 4e95d9fb8422
Create Date: 2026-04-26 16:49:40.638530

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a84a83fa266a'
down_revision: Union[str, Sequence[str], None] = '4e95d9fb8422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scustom', sa.Column('password', sa.String(length=20), nullable=True))
    op.alter_column('sflight', 'fldate',
               existing_type=sa.DATE())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sflight', 'fldate',
               existing_type=sa.DATE())
    op.drop_column('scustom', 'password')
    # ### end Alembic commands ###
